# -*- coding: utf-8 -*-
"""Greenhouse_Gas_Emissions_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcvMpAK6jo83qu1RVV0GqIACqAsa3UUq
"""

import matplotlib.pyplot as plt

class EmissionTracker:
    def __init__(self):
        self.data = {}

    def add_emission(self, sector, year, emissions):
        if sector not in self.data:
            self.data[sector] = {}
        self.data[sector][year] = emissions

    def plot_emissions(self):
        for sector, emissions in self.data.items():
            years = sorted(emissions.keys())
            values = [emissions[year] for year in years]
            plt.plot(years, values, label=sector)

        plt.xlabel('Year')
        plt.ylabel('Emissions (kg CO2)')
        plt.title('Greenhouse Gas Emissions Over Time')
        plt.legend()
        plt.show()

# Example usage
tracker = EmissionTracker()
tracker.add_emission("Transportation", 2023, 2000)
tracker.add_emission("Transportation", 2024, 2100)
tracker.add_emission("Energy", 2023, 3000)
tracker.add_emission("Energy", 2024, 2800)

tracker.plot_emissions()